name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-1.23-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-1.23-
    
    - name: Download dependencies
      run: go mod download
    
    - name: Run tests
      run: go test -v ./...
    
    - name: Build binaries
      run: |
        # Linux amd64
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o ghm-linux-amd64 ./cmd/ghm
        
        # Linux arm64
        GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o ghm-linux-arm64 ./cmd/ghm
        
        # macOS amd64
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o ghm-darwin-amd64 ./cmd/ghm
        
        # macOS arm64
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o ghm-darwin-arm64 ./cmd/ghm
    
    - name: Create archives
      run: |
        # Linux amd64
        tar -czf ghm-linux-amd64.tar.gz ghm-linux-amd64
        
        # Linux arm64
        tar -czf ghm-linux-arm64.tar.gz ghm-linux-arm64
        
        # macOS amd64
        tar -czf ghm-darwin-amd64.tar.gz ghm-darwin-amd64

        # macOS arm64
        tar -czf ghm-darwin-arm64.tar.gz ghm-darwin-arm64

    - name: Generate checksums
      run: |
        sha256sum ghm-linux-amd64.tar.gz > checksums.txt
        sha256sum ghm-linux-arm64.tar.gz >> checksums.txt
        sha256sum ghm-darwin-amd64.tar.gz >> checksums.txt
        sha256sum ghm-darwin-arm64.tar.gz >> checksums.txt

    - name: Extract tag name
      id: tag
      run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag.outputs.tag }}
        name: Release ${{ steps.tag.outputs.tag }}
        draft: false
        prerelease: false
        generate_release_notes: true
        files: |
          ghm-linux-amd64.tar.gz
          ghm-linux-arm64.tar.gz
          ghm-darwin-amd64.tar.gz
          ghm-darwin-arm64.tar.gz
          checksums.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Homebrew Formula
      run: |
        if [ -z "${HOMEBREW_TAP_TOKEN}" ]; then
          echo "⚠️ HOMEBREW_TAP_TOKEN not set. Skipping Homebrew formula update."
          echo "ℹ️ To enable automatic Homebrew updates, please set up HOMEBREW_TAP_TOKEN secret."
          echo "ℹ️ See HOMEBREW_SETUP.md for detailed instructions."
          exit 0
        fi

        echo "🍺 Updating Homebrew formula..."
        chmod +x scripts/update-homebrew.sh
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        ./scripts/update-homebrew.sh ${{ steps.tag.outputs.tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
      if: ${{ !contains(steps.tag.outputs.tag, '-') }}